[project]
name = "slm"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "datasets>=4.4.0",
    "torch>=2.8.0",
    "tqdm>=4.67.1",
    "transformers>=4.55.4",
    "accelerate>=1.10.0",
]
